### PR TITLE
Upgrade to latest canvas to build with latest NodeJS

### PR DESCRIPTION
**Pull request by WilliamRClark**
This is to address the build failure on Windows with the latest version of NodeJS.   

Canvas updated their api in v2.0 thus the other changes to maintain compatibility.

Fixes https://github.com/noflo/noflo-canvas/issues/191

### CODE REVIEW

**Review by WilliamRClark — COMMENTED** [review]
The lack of a package-lock.json indicates this was built with an older version of NPM / Node.

**Comment by bergie** [comment]
Looks great! However, please remove the lock file from the PR

**Comment by WilliamRClark** [comment]
> Looks great! However, please remove the lock file from the PR

Absolutely.

**Comment by WilliamRClark** [comment]
@bergie  Lock file removed.

**Pull request merged**
